// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkYezyCGG9Aqli3NBjor3rBGnTf7fjXLw',
    appId: '1:224788759385:android:50a6d0e3384ee4cad18248',
    messagingSenderId: '224788759385',
    projectId: 'fir-tutorial-9d2b1',
    databaseURL: 'https://fir-tutorial-9d2b1-default-rtdb.firebaseio.com',
    storageBucket: 'fir-tutorial-9d2b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFvQPgc4o4lJZJtHY4Jl6GLv8qwsQ8SD4',
    appId: '1:224788759385:ios:04195cbe48f7015cd18248',
    messagingSenderId: '224788759385',
    projectId: 'fir-tutorial-9d2b1',
    databaseURL: 'https://fir-tutorial-9d2b1-default-rtdb.firebaseio.com',
    storageBucket: 'fir-tutorial-9d2b1.appspot.com',
    androidClientId: '224788759385-gk6fehi23aun58kb77i1dbauh2dnj00n.apps.googleusercontent.com',
    iosClientId: '224788759385-ftehib1ugqqshusvb4f5nl30ice1slft.apps.googleusercontent.com',
    iosBundleId: 'com.sharma.educationApp',
  );

}